### ISSUE TITLE
We should use `spring-kafka-test` in `multibinder` sample

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-samples#27]
See https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/102#issuecomment-280836675 for details.

**Comment by erasmas** [comment]
Hello,

I was looking at samples and docs to understand how to write a unit test that would use `EmbeddedKafka` but I can't get `multibinder` to compile because of two issues.

- `EmbeddedKafka` cannot be resolved, probably because `spring-kafka-test` is not listed in dependencies
- Compilation fails due to `... RabbitAndKafkaBinderApplicationTests.java:[86,30] type org.springframework.cloud.stream.binder.BinderFactory does not take parameters`

I'll be happy to submit a fix as soon I know how to fix this compilation error.

**Comment by sabbyanandan** [comment]
The multi-binder support had evolved significantly, so what we have here is significantly outdated.
