### ISSUE TITLE
How could I change an iterator type to use a kinesis?

### ISSUE THREAD

**Issue by juneng603** [spring-cloud/spring-cloud-stream-samples#52]
Hi, 

I want to change a kinesis default iterator type(latest) to another, but I leave a question because it is difficult to find a sample code. 

I'd appreciate it if you could tell me what to do.
Sharing it with sample codes would be great.

**Comment by artembilan** [comment]
Well, that's just out of support. We do only `latest` by default.

Feel free to raise an issue against https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis project. But, please, provide as much arguments as possible and how that can be useful in fields.

Thanks

P.S. Closing as there really nothing to show. When the fix is in the library, we will update the Kinesis sample to demonstrate the configuration property.

**Comment by juneng603** [comment]
@artembilan thanks for a your quick reply. 👍
