### ISSUE TITLE
Can producer code be used in maven....not in spring boot

### ISSUE THREAD

**Issue by dhruvpanwar95** [spring-cloud/spring-cloud-stream-samples#58]
I want to produce messages to stream in already existing application which is in maven only .But I want to use message channel in maven not in spring boot.Is it possible?If yes ....please share the code

**Comment by olegz** [comment]
@dhruvpanwar95 Maven is a general build/dependency management tool, so I am not exactly sure what are you asking. What do you mean when you say _...message channel in maven..._? Neither channels nor any other application configuration is provided in maven. Could you please clarify?

**Comment by vikrantch-hk** [comment]
@olegz we were actually trying to port OrderSource code from 'spring-cloud-stream-samples/kinesis-produce-consume' to one of our non spring boot projects, we have defined stream binders output channels and source in the same way as in 'kinesis-produce-consume' and added all the dependencies. But app context is failing in startup and is unable to find bean implementation for OrderProcessor. Is there any specific listener or something which should be added to non spring boot projects in order to use spring cloud stream.

**Comment by olegz** [comment]
I am not familiar with kinesis binder or app so I am tagging my friend @artembilan  who is definitely more familiar with it. 
That said, if I understand you correctly your issue is some miss-connection between the applications contexts and without seeing the actual code it would be hard to understand the issue

**Comment by vikrantch-hk** [comment]
@olegz yeah you are correct there is some mess in app context. @dhruvpanwar95 please add some code snippet and startup logs

**Comment by dhruvpanwar95** [comment]
I added dependency in my maven project 
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream</artifactId>
			<version>1.3.2.RELEASE</version>
</dependency>

16-Feb-2018 19:43:39.518 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
16-Feb-2018 19:43:39.529 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
================  SHUTTING DOWN  ==================
16-Feb-2018 19:43:39.593 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-7070"]
16-Feb-2018 19:43:39.636 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-7009"]
16-Feb-2018 19:43:39.641 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 24326 ms

**Comment by artembilan** [comment]
@vikrantch-hk , @dhruvpanwar95 ,

Please, be advised that Spring Cloud Stream is fully Spring Boot based, and all its stuff just can't work outside of Spring Boot environment.

More over that's already not this project issue.

Would be better to ask questions on StackOverflow.

Also, please, consider to make yourself familiar with GitHub [comments style](https://help.github.com/articles/basic-writing-and-formatting-syntax/). Right now all your comments are not readable therefore it's hard to help you. 

Thank you for understanding.

*Closing as Invalid*
