### ISSUE TITLE
How to add new property to application.yml file

### ISSUE THREAD

**Issue by chayanappsbee** [spring-cloud/spring-cloud-stream-samples#62]
How to add following properties :
1. autoAddShards
2. minShardCount

in application.yml

**Comment by artembilan** [comment]
First of all would be better to be more precise with the description and properly point to the requested sample or at least project you would like to develop against.

Well, to be more clear: this kind of questions should be handled in StackOverflow.

That's your luck I know that the story is about AWS Kinesis, so I will answer to you.
But at the same time that's your own fault you haven't get an answer yet. Just because of lack of description in the question.

Just be as clear as possible in the future, please!

So, according AWS Kinesis Binder [Documentation](https://github.com/spring-cloud/spring-cloud-stream-binder-aws-kinesis/blob/master/spring-cloud-stream-binder-kinesis-docs/src/main/asciidoc/overview.adoc#configuration-options) we have:

    spring:
      cloud:
        stream:
          kinesis:
            binder:
              autoAddShards: true
              minShardCount: 10

Does it make sense for you?

If you think we have a problem with documentation, please, raise an appropriate issue in the proper project.

Thanks for understanding

**Comment by chayanappsbee** [comment]
Sorry for not making the point clear. I am following the kinesis-produce-consume project and the following is the application.yml code snippet :

spring:
  cloud:
    stream:
      bindings:
        ordersOut: 
          destination: test_stream
          content-type: application/json
          producer: 
            partitionKeyExpression: "1" 
        ordersIn:
          destination: test_stream
          content-type: application/json

If I want to have include autoAddShards and minShardCount properties where to add it.

Thanks for your assistance

**Comment by artembilan** [comment]
Yeah... Seems for me I answered to you how to do that...
Anyway: `Closed as Invalid` in favor of https://stackoverflow.com/questions/49313884/how-to-add-new-property-to-application-yml-file
