### ISSUE TITLE
Validate interactive query works with multiple Kafka streams app instances

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-samples#68]
When there are multiple instances of the same kafka stream application and interactive query feature is used across all of them, we need to verify that this type of querying is possible through the support in spring cloud stream. Use this sample as a reference for this validation: https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-interactive-query-advanced

**Comment by arslanakhtar61** [comment]
Hi sobychacko,

Is it possible to use interactive query (InteractiveQueryService) within the class with @EnableBinding annotation or within the method with @StreamListener? I tried instantiating ReadOnlyKeyValueStore within yours provided KStreamMusicSampleApplication class and process method but its always null.

Actually, my use case is that my @StreamListener method is listening to a bunch of KTables and KStreams and during the process topology e.g filtering, I have to check whether the key from a KStream already exists in a particular KTable. 

I tried to figure out how to scan an incoming KTable to check if a key already exists but no luck. Then I came across InteractiveQueryService whose get() method could be used to check if a key exists inside a state store materializedAs from a KTable. The problem is that I can't access it from with the process topology (@EnableBinding or @StreamListener). It can only be accessed from outside these annotation e.g RestController.

Could you kindly suggest a solution? Is there a way to scan an incoming KTable to check for the existence of a key or value if not then could we access InteractiveQueryService within the process topology. Thanks

**Comment by sobychacko** [comment]
@arslanakhtar61 I think you asked the same question on SO as well. I answered there. Please see if that gives you a solution.

**Comment by arslanakhtar61** [comment]
Thanks a lot for the solution on [StackOverflow](https://stackoverflow.com/questions/55931237/how-to-use-interactive-query-within-kafka-process-topology-in-spring-cloud-strea). It helped a lot.

**Comment by arslanakhtar61** [comment]
Hi sobychacko,

I have raised another problem related to querying state stores in spring-cloud-stream here:
https://stackoverflow.com/questions/56056368/spring-cloud-stream-process-kafka-messages-only-after-the-state-stores-materiali

Appreciate if you could provide a solution to this issue. Thanks

**Comment by sobychacko** [comment]
@arslanakhtar61 Normal Kafka Streams behavior is not to begin processing any records until the state stores are fully populated. I wonder why this is not the case for you. Can you re-create this same behavior without involving Spring at all (as a straight Kafka Streams application)?

**Comment by arslanakhtar61** [comment]
Before I create a simple kafka application, I tried to replicate the issue by modifying one of your spring-cloud-stream sample at https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-global-table-join

I have pushed the modified version at here: https://github.com/arslanakhtar61/kafka-streams-global-table-join

I have added a new topic and modified the producer to generate messages into the new topic. I am using a transformer from the processing API with Kafka stream integration in order to access the materialized stateStore during stream processing. For debugging purpose, I outputted the results from within the UserTransformer.java class and persisted the outputs in the following file: https://github.com/arslanakhtar61/kafka-streams-global-table-join/blob/master/result.txt

Before starting the application 2nd time, I would re-run the producer.java to generate fresh unprocessed messages. As you can see from the result.txt file, the 1st application run has empty stateStore and after stopping and restarting the application again with new messages in the topics, the stateStore is fully populated.

**Comment by sobychacko** [comment]
@arslanakhtar61 I will look into it and get back to you. Thank you!

**Comment by sobychacko** [comment]
@arslanakhtar61 Are you saying that you are not seeing the data materialized the first time you are running the app? Could you also specify once again what the issues are and the expected behavior?

**Comment by arslanakhtar61** [comment]
Yes @sobychacko, so when I run the application 1st time, the console output from the UserTrasnformer.java class is:
`
1st Run Console Output:

UserTransformer Message => Key: americas, Value: 4
UserTransformer => keyValueStore..approximateNumEntries(): 0
UserTransformer => regionTopExport: null
UserTransformer Message => Key: asia, Value: 25
UserTransformer => keyValueStore..approximateNumEntries(): 0
UserTransformer => regionTopExport: null
UserTransformer Message => Key: americas, Value: 19
UserTransformer => keyValueStore..approximateNumEntries(): 0
UserTransformer => regionTopExport: null
UserTransformer Message => Key: europe, Value: 56
UserTransformer => keyValueStore..approximateNumEntries(): 0
UserTransformer => regionTopExport: null
UserTransformer Message => Key: americas, Value: 78
UserTransformer => keyValueStore..approximateNumEntries(): 0
UserTransformer => regionTopExport: null
UserTransformer Message => Key: europe, Value: 40
UserTransformer => keyValueStore..approximateNumEntries(): 0
UserTransformer => regionTopExport: null
UserTransformer Message => Key: asia, Value: 99
UserTransformer => keyValueStore..approximateNumEntries(): 0
UserTransformer => regionTopExport: null
`
As you can see above  the keyValueStore is empty as it has approximateNumEntries(): 0 and the .get(key) method of keyValueStore is returning null e.g "regionTopExport: null". This is not expected. The messages are arriving before the stateStore have been fullly populated but regardless the incomming messages are still processed and commited back to kafka.

After stopping the app, re-running producer.java to generate unprocessed messages, then re-running the app the 2nd time, the console output from the UserTrasnformer.java class is:
`
2nd Run Console Output:

UserTransformer Message => Key: americas, Value: 4
UserTransformer => keyValueStore..approximateNumEntries(): 3
UserTransformer => regionTopExport: coffee
UserTransformer Message => Key: asia, Value: 25
UserTransformer => keyValueStore..approximateNumEntries(): 3
UserTransformer => regionTopExport: apples
UserTransformer Message => Key: americas, Value: 19
UserTransformer => keyValueStore..approximateNumEntries(): 3
UserTransformer => regionTopExport: coffee
UserTransformer Message => Key: europe, Value: 56
UserTransformer => keyValueStore..approximateNumEntries(): 3
UserTransformer => regionTopExport: eggs
UserTransformer Message => Key: americas, Value: 78
UserTransformer => keyValueStore..approximateNumEntries(): 3
UserTransformer => regionTopExport: coffee
UserTransformer Message => Key: europe, Value: 40
UserTransformer => keyValueStore..approximateNumEntries(): 3
UserTransformer => regionTopExport: eggs
UserTransformer Message => Key: asia, Value: 99
UserTransformer => keyValueStore..approximateNumEntries(): 3
UserTransformer => regionTopExport: apples
`

Now the keyValueStore is not empty because of "approximateNumEntries(): 3" and also the .get(key) method of the keyValueStore is returning expected values (non-null e.g "regionTopExport: apples") from the materialized stateStore named as "all-region-top-exports". The result from processing messages on the 2nd application run is the expected outcome.

Am I missing any spring-cloud-stream configuration or is there a coding issue which is causing this behavior? Thanks

**Comment by sobychacko** [comment]
@arslanakhtar61 My guess is that this is probably a timing issue with the test setup. It looks like by the time stream processing gets started from the user clicks topic, Kafka Streams hasn't started processing from the table yet (_when you run the application for the very first time_). This is why you are getting the value as null there. But with the second time onward, there is already data in the state store and that gets populated. Since `user-clicks` is the first one to be populated in your Producer class, Kafka starts with that. Can you put the code where you populate the `regionTopExport` topic as the very first thing in your test Producer? I guess in that case, Kafka processes that as first and you will see the data printed out from your transformer when you send the user-click data. I think this is a test only issue. You will most likely be able to fix this testing issue by using this workaround. If this issue  happens in a real world scenario, we can take a look further.

**Comment by arslanakhtar61** [comment]
@sobychacko. Thanks for the insight. I refactored the Producer.java code so that the messages for the topic "region-top-exports" from which the stateStore will be materializedAs on app startup, is generated first to give the messages a smaller timestamp before messages in other topics are generated (giving them bigger timestamp). Messages with a smaller timestamp are processed first and thus it should populate the stateStore.

This solves the stream messages timing issue: Console result:
`
1st Run Console Output => Producer generate topic messages in order (region-top-exports, user-clicks3, user-regions)

UserTransformer Message => Key: europe, Value: 13
UserTransformer => keyValueStore.approximateNumEntries(): 0
UserTransformer => regionTopExport = keyValueStore.get(europe): eggs
UserTransformer Message => Key: americas, Value: 4
UserTransformer => keyValueStore.approximateNumEntries(): 0
UserTransformer => regionTopExport = keyValueStore.get(americas): coffee
UserTransformer Message => Key: asia, Value: 25
UserTransformer => keyValueStore.approximateNumEntries(): 0
UserTransformer => regionTopExport = keyValueStore.get(asia): apples
UserTransformer Message => Key: americas, Value: 19
UserTransformer => keyValueStore.approximateNumEntries(): 0
UserTransformer => regionTopExport = keyValueStore.get(americas): coffee
UserTransformer Message => Key: europe, Value: 56
UserTransformer => keyValueStore.approximateNumEntries(): 0
UserTransformer => regionTopExport = keyValueStore.get(europe): eggs
UserTransformer Message => Key: americas, Value: 78
UserTransformer => keyValueStore.approximateNumEntries(): 0
UserTransformer => regionTopExport = keyValueStore.get(americas): coffee
UserTransformer Message => Key: europe, Value: 40
UserTransformer => keyValueStore.approximateNumEntries(): 0
UserTransformer => regionTopExport = keyValueStore.get(europe): eggs
UserTransformer Message => Key: asia, Value: 99
UserTransformer => keyValueStore.approximateNumEntries(): 0
UserTransformer => regionTopExport = keyValueStore.get(asia): apples
`
Regarding test issue scenerio, Actually I encountered this stream timing issue in a real world scenario (while working on a project for my company using spring-cloud-stream). I was wondering this is not a bug right? and the safe way to fix this for production use case is to generate messages for topics in correct order?

**Comment by sobychacko** [comment]
@arslanakhtar61 I don't think this is a bug. I am sure if you try the same app directly as a Kafka Streams app (without including Spring Cloud Stream binder), you might still see the same behavior. You may want to ask on SO and tag Kafka Streams to see if there are any recommended config options to fix this.

**Comment by arslanakhtar61** [comment]
@sobychacko The sample application with a small stateStore topic (e.g around 100 messages) works fine as demonstrated above but when I try to materializedAs stateStore from a comparatively larger topic (e.g around 10,000 messages), The same issue is arising. This time I made sure that the stream timing issue was avoided by producing messages for stateStore topics with a smaller timestamp.

I am using confluent JDBC source connect to read db tables data into kafka topics. Some tables are small in row size while others are quite large in row numbers. During stream processing/transform, It appears that on the first time application startup, the smaller stateStore works fine as it is not empty, but the larger stateStore is still empty on app startup giving wrong results. However, on the 2nd time app startup, the larger stateStore works fine as its now non empty and fully populated. 

Is there a limit on topic size from which a stateStore materializedAs on app startup will work as expected? Thanks

**Comment by arslanakhtar61** [comment]
I got it working by overriding the kafka client and kafka streams dependency to latest version:
https://stackoverflow.com/questions/56231946/the-latest-version-fishtown-sr2-spring-cloud-stream-doesnt-support-kafka-cli

**Comment by sabbyanandan** [comment]
Stale issue; closing it.
